### ISSUE TITLE
Unable To Start Activity , Can't Make Instance of class

### ISSUE THREAD

**Issue by Ansh1248163264** [chaquo/chaquopy-console#7]
```
FATAL EXCEPTION: main
Process: com.example.demo, PID: 11456
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.demo/com.example.demo.MainActivity}: java.lang.RuntimeException: Cannot create an instance of class com.example.demo.MainActivity$Task
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.RuntimeException: Cannot create an instance of class com.example.demo.MainActivity$Task
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:320)
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
	at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
	at com.example.demo.utils.ConsoleActivity.onCreate(ConsoleActivity.java:74)
	at com.example.demo.utils.PythonConsoleActivity.onCreate(PythonConsoleActivity.java:25)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Activity.performCreate(Activity.java:8270)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201) 
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:226) 
	at android.os.Looper.loop(Looper.java:313) 
	at android.app.ActivityThread.main(ActivityThread.java:8663) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312)
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304) 
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278) 
	at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128) 
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187) 
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153) 
	at com.example.demo.utils.ConsoleActivity.onCreate(ConsoleActivity.java:74) 
	at com.example.demo.utils.PythonConsoleActivity.onCreate(PythonConsoleActivity.java:25) 
	at android.app.Activity.performCreate(Activity.java:8290) 
	at android.app.Activity.performCreate(Activity.java:8270) 
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329) 
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009) 
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201) 
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:226) 
	at android.os.Looper.loop(Looper.java:313) 
	at android.app.ActivityThread.main(ActivityThread.java:8663) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
Caused by: java.lang.RuntimeException: Cannot use GenericPlatform on Android. Call Python.start(new AndroidPlatform(context)) before using Python, or use PyApplication to do this automatically.
	at com.chaquo.python.GenericPlatform.<init>(GenericPlatform.java:11)
	at com.chaquo.python.Python.getInstance(Python.java:33)
	at com.example.demo.utils.PythonConsoleActivity$Task.<init>(PythonConsoleActivity.java:50)
	at com.example.demo.utils.PythonConsoleActivity$Task.<init>(PythonConsoleActivity.java:58)
	at com.example.demo.MainActivity$Task.<init>(MainActivity.java:22)
	at java.lang.reflect.Constructor.newInstance0(Native Method) 
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312) 
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304) 
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278) 
	at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128) 
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187) 
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153) 
	at com.example.demo.utils.ConsoleActivity.onCreate(ConsoleActivity.java:74) 
	at com.example.demo.utils.PythonConsoleActivity.onCreate(PythonConsoleActivity.java:25) 
	at android.app.Activity.performCreate(Activity.java:8290) 
	at android.app.Activity.performCreate(Activity.java:8270) 
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329) 
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009) 
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201) 
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:226) 
	at android.os.Looper.loop(Looper.java:313) 
	at android.app.ActivityThread.main(ActivityThread.java:8663) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
```

**Comment by Ansh1248163264** [comment]
Hello Again Respected Sir, I Want To Inform That  When I Was Trying To completely copy your codes into my project for testing , my project crashes on runtime by stating that unable to make instance of Main Activity class , PLEASE HELP

**Comment by mhsmith** [comment]
The chaquopy-console app starts Python by using `PyApplication` in its AndroidManifest file. If you're copying parts of it into a different app, then you'll have to either do the same, or use one of the other Python startup methods described [here](https://chaquo.com/chaquopy/doc/current/android.html#android-startup).

**Comment by Ansh1248163264** [comment]
Yeah , finally just got it ....... Thanks For Making Such A Beauty #Chaquopy .....
